apiVersion: 1

datasources:

  # ── Loki (logs) ──────────────────────────────────────────────────────────────
  - name:      Loki
    type:      loki
    uid:       loki
    access:    proxy
    url:       http://loki:3100
    isDefault: false
    jsonData:
      maxLines:          1000
      derivedFields:
        - name:          TraceID
          matcherRegex:  '"TraceId":"(\w+)"'
          url:           "$${__value.raw}"
          datasourceUid: tempo

  # ── Tempo (traces) ───────────────────────────────────────────────────────────
  - name:      Tempo
    type:      tempo
    uid:       tempo
    access:    proxy
    url:       http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid:  loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift:   "1m"
        filterByTraceID: true
        filterBySpanID:  false
      serviceMap:
        datasourceUid: prometheus
      lokiSearch:
        datasourceUid: loki

  # ── Prometheus (metrics) ─────────────────────────────────────────────────────
  - name:      Prometheus
    type:      prometheus
    uid:       prometheus
    access:    proxy
    url:       http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod:        POST
      exemplarTraceIdDestinations:
        - name:          traceID
          datasourceUid: tempo
